<main id="blog">
    <ul>
    <?php foreach ($data["articles"] as $id => $article) : ?>
        <li>
            <article>
                <header>
                    <h2>
                        <?= $article["titre"] ?>
                    </h2>
                </header>

                <section>
                    <p>
                        <?= $article["resume"] ?>
                    </p>
                </section>

                <footer>
                    <a href="?route=article&id=<?= $id ?>">
                        Lire l'article complet
                    </a>
                </footer>
            </article>
        </li>
    <?php endforeach; ?>
    </ul>
</main>