<main>
    <form method="post" action="/">
        <fieldset>
            <label for="email">
                Email
            </label>
            <input type="email" id="email" name="email" />
        </fieldset>
        <fieldset>
            <label for="password">
                Mot de passe
            </label>
            <input type="password" id="password" name="password" />
        </fieldset>
        <fieldset>
            <button type="submit">Connexion</button>
        </fieldset>
    </form>
</main>